stages:
  - test
  - publish

test-lint:
  stage: test
  image: node:10
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  before_script:
    - npm install
  script:
    - npm run lint
    - npm run test:cover
  except:
    - tags

npm-publish:
  stage: publish
  image: node:10
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - tags