codecov:
  require_ci_to_pass: false

coverage:
  range: 60..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        # Allow decreasing 2% of total coverage to avoid noise.
        threshold: 2%
        if_ci_failed: error
        informational: true
        paths:
          - "src"
          - "!proto/*"
          - "!examples/*"
          - "!lib/*"
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: true
        paths:
        - "src"
        - "!proto/*"
        - "!examples/*"
        - "!lib/*"

# https://docs.codecov.io/docs/codecovyml-reference#section-parsers
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

ignore:
  - proto/*
  - lib/*
  - examples/*
