/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var protos_common_account_pb = require('../../protos/common/account_pb.js');
var protos_common_call_pb = require('../../protos/common/call_pb.js');
var protos_common_chain_pb = require('../../protos/common/chain_pb.js');
var protos_common_error_pb = require('../../protos/common/error_pb.js');
var protos_ethereum_transaction_pb = require('../../protos/ethereum/transaction_pb.js');
var protos_ethereum_receipt_pb = require('../../protos/ethereum/receipt_pb.js');
goog.exportSymbol('proto.trace.Metadata', null, global);
goog.exportSymbol('proto.trace.Trace', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.trace.Metadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.trace.Metadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.trace.Metadata.displayName = 'proto.trace.Metadata';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.trace.Metadata.prototype.toObject = function(opt_includeInstance) {
  return proto.trace.Metadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.trace.Metadata} msg The msg instance to transform.
 * @return {!Object}
 */
proto.trace.Metadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.trace.Metadata}
 */
proto.trace.Metadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.trace.Metadata;
  return proto.trace.Metadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.trace.Metadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.trace.Metadata}
 */
proto.trace.Metadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.trace.Metadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.trace.Metadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.trace.Metadata} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.trace.Metadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.trace.Metadata.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.trace.Metadata.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * map<string, string> extra = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.trace.Metadata.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


proto.trace.Metadata.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.trace.Trace = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.trace.Trace.repeatedFields_, null);
};
goog.inherits(proto.trace.Trace, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.trace.Trace.displayName = 'proto.trace.Trace';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.trace.Trace.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.trace.Trace.prototype.toObject = function(opt_includeInstance) {
  return proto.trace.Trace.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.trace.Trace} msg The msg instance to transform.
 * @return {!Object}
 */
proto.trace.Trace.toObject = function(includeInstance, msg) {
  var f, obj = {
    chain: (f = msg.getChain()) && protos_common_chain_pb.Chain.toObject(includeInstance, f),
    sender: (f = msg.getSender()) && protos_common_account_pb.Account.toObject(includeInstance, f),
    receiver: (f = msg.getReceiver()) && protos_common_account_pb.Account.toObject(includeInstance, f),
    call: (f = msg.getCall()) && protos_common_call_pb.Call.toObject(includeInstance, f),
    tx: (f = msg.getTx()) && protos_ethereum_transaction_pb.Transaction.toObject(includeInstance, f),
    receipt: (f = msg.getReceipt()) && protos_ethereum_receipt_pb.Receipt.toObject(includeInstance, f),
    errorsList: jspb.Message.toObjectList(msg.getErrorsList(),
    protos_common_error_pb.Error.toObject, includeInstance),
    metadata: (f = msg.getMetadata()) && proto.trace.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.trace.Trace}
 */
proto.trace.Trace.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.trace.Trace;
  return proto.trace.Trace.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.trace.Trace} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.trace.Trace}
 */
proto.trace.Trace.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protos_common_chain_pb.Chain;
      reader.readMessage(value,protos_common_chain_pb.Chain.deserializeBinaryFromReader);
      msg.setChain(value);
      break;
    case 2:
      var value = new protos_common_account_pb.Account;
      reader.readMessage(value,protos_common_account_pb.Account.deserializeBinaryFromReader);
      msg.setSender(value);
      break;
    case 3:
      var value = new protos_common_account_pb.Account;
      reader.readMessage(value,protos_common_account_pb.Account.deserializeBinaryFromReader);
      msg.setReceiver(value);
      break;
    case 4:
      var value = new protos_common_call_pb.Call;
      reader.readMessage(value,protos_common_call_pb.Call.deserializeBinaryFromReader);
      msg.setCall(value);
      break;
    case 5:
      var value = new protos_ethereum_transaction_pb.Transaction;
      reader.readMessage(value,protos_ethereum_transaction_pb.Transaction.deserializeBinaryFromReader);
      msg.setTx(value);
      break;
    case 6:
      var value = new protos_ethereum_receipt_pb.Receipt;
      reader.readMessage(value,protos_ethereum_receipt_pb.Receipt.deserializeBinaryFromReader);
      msg.setReceipt(value);
      break;
    case 7:
      var value = new protos_common_error_pb.Error;
      reader.readMessage(value,protos_common_error_pb.Error.deserializeBinaryFromReader);
      msg.addErrors(value);
      break;
    case 8:
      var value = new proto.trace.Metadata;
      reader.readMessage(value,proto.trace.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.trace.Trace.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.trace.Trace.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.trace.Trace} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.trace.Trace.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChain();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protos_common_chain_pb.Chain.serializeBinaryToWriter
    );
  }
  f = message.getSender();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protos_common_account_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getReceiver();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      protos_common_account_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getCall();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      protos_common_call_pb.Call.serializeBinaryToWriter
    );
  }
  f = message.getTx();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      protos_ethereum_transaction_pb.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getReceipt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      protos_ethereum_receipt_pb.Receipt.serializeBinaryToWriter
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      protos_common_error_pb.Error.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.trace.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.Chain chain = 1;
 * @return {?proto.common.Chain}
 */
proto.trace.Trace.prototype.getChain = function() {
  return /** @type{?proto.common.Chain} */ (
    jspb.Message.getWrapperField(this, protos_common_chain_pb.Chain, 1));
};


/** @param {?proto.common.Chain|undefined} value */
proto.trace.Trace.prototype.setChain = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.trace.Trace.prototype.clearChain = function() {
  this.setChain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasChain = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional common.Account sender = 2;
 * @return {?proto.common.Account}
 */
proto.trace.Trace.prototype.getSender = function() {
  return /** @type{?proto.common.Account} */ (
    jspb.Message.getWrapperField(this, protos_common_account_pb.Account, 2));
};


/** @param {?proto.common.Account|undefined} value */
proto.trace.Trace.prototype.setSender = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.trace.Trace.prototype.clearSender = function() {
  this.setSender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasSender = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.Account receiver = 3;
 * @return {?proto.common.Account}
 */
proto.trace.Trace.prototype.getReceiver = function() {
  return /** @type{?proto.common.Account} */ (
    jspb.Message.getWrapperField(this, protos_common_account_pb.Account, 3));
};


/** @param {?proto.common.Account|undefined} value */
proto.trace.Trace.prototype.setReceiver = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.trace.Trace.prototype.clearReceiver = function() {
  this.setReceiver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasReceiver = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional common.Call call = 4;
 * @return {?proto.common.Call}
 */
proto.trace.Trace.prototype.getCall = function() {
  return /** @type{?proto.common.Call} */ (
    jspb.Message.getWrapperField(this, protos_common_call_pb.Call, 4));
};


/** @param {?proto.common.Call|undefined} value */
proto.trace.Trace.prototype.setCall = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.trace.Trace.prototype.clearCall = function() {
  this.setCall(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasCall = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ethereum.Transaction tx = 5;
 * @return {?proto.ethereum.Transaction}
 */
proto.trace.Trace.prototype.getTx = function() {
  return /** @type{?proto.ethereum.Transaction} */ (
    jspb.Message.getWrapperField(this, protos_ethereum_transaction_pb.Transaction, 5));
};


/** @param {?proto.ethereum.Transaction|undefined} value */
proto.trace.Trace.prototype.setTx = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.trace.Trace.prototype.clearTx = function() {
  this.setTx(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasTx = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ethereum.Receipt receipt = 6;
 * @return {?proto.ethereum.Receipt}
 */
proto.trace.Trace.prototype.getReceipt = function() {
  return /** @type{?proto.ethereum.Receipt} */ (
    jspb.Message.getWrapperField(this, protos_ethereum_receipt_pb.Receipt, 6));
};


/** @param {?proto.ethereum.Receipt|undefined} value */
proto.trace.Trace.prototype.setReceipt = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.trace.Trace.prototype.clearReceipt = function() {
  this.setReceipt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasReceipt = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated common.Error errors = 7;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.common.Error>}
 */
proto.trace.Trace.prototype.getErrorsList = function() {
  return /** @type{!Array.<!proto.common.Error>} */ (
    jspb.Message.getRepeatedWrapperField(this, protos_common_error_pb.Error, 7));
};


/** @param {!Array.<!proto.common.Error>} value */
proto.trace.Trace.prototype.setErrorsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.common.Error=} opt_value
 * @param {number=} opt_index
 * @return {!proto.common.Error}
 */
proto.trace.Trace.prototype.addErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.common.Error, opt_index);
};


proto.trace.Trace.prototype.clearErrorsList = function() {
  this.setErrorsList([]);
};


/**
 * optional Metadata metadata = 8;
 * @return {?proto.trace.Metadata}
 */
proto.trace.Trace.prototype.getMetadata = function() {
  return /** @type{?proto.trace.Metadata} */ (
    jspb.Message.getWrapperField(this, proto.trace.Metadata, 8));
};


/** @param {?proto.trace.Metadata|undefined} value */
proto.trace.Trace.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.trace.Trace.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.trace.Trace.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 8) != null;
};


goog.object.extend(exports, proto.trace);
