/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var types_abi_abi_pb = require('../../types/abi/abi_pb.js');
goog.object.extend(proto, types_abi_abi_pb);
var types_common_account_pb = require('../../types/common/account_pb.js');
goog.object.extend(proto, types_common_account_pb);
goog.exportSymbol('proto.contractregistry.AddressUpdateRequest', null, global);
goog.exportSymbol('proto.contractregistry.AddressUpdateResponse', null, global);
goog.exportSymbol('proto.contractregistry.GetContractABIResponse', null, global);
goog.exportSymbol('proto.contractregistry.GetContractBytecodeResponse', null, global);
goog.exportSymbol('proto.contractregistry.GetContractDeployedBytecodeResponse', null, global);
goog.exportSymbol('proto.contractregistry.GetContractRequest', null, global);
goog.exportSymbol('proto.contractregistry.GetEventsBySigHashRequest', null, global);
goog.exportSymbol('proto.contractregistry.GetEventsBySigHashResponse', null, global);
goog.exportSymbol('proto.contractregistry.GetMethodsBySelectorRequest', null, global);
goog.exportSymbol('proto.contractregistry.GetMethodsBySelectorResponse', null, global);
goog.exportSymbol('proto.contractregistry.RegisterContractRequest', null, global);
goog.exportSymbol('proto.contractregistry.RegisterContractResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.RegisterContractRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.RegisterContractRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.RegisterContractRequest.displayName = 'proto.contractregistry.RegisterContractRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.RegisterContractResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.RegisterContractResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.RegisterContractResponse.displayName = 'proto.contractregistry.RegisterContractResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetContractRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.GetContractRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetContractRequest.displayName = 'proto.contractregistry.GetContractRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetContractABIResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.GetContractABIResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetContractABIResponse.displayName = 'proto.contractregistry.GetContractABIResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetContractBytecodeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.GetContractBytecodeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetContractBytecodeResponse.displayName = 'proto.contractregistry.GetContractBytecodeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetContractDeployedBytecodeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.GetContractDeployedBytecodeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetContractDeployedBytecodeResponse.displayName = 'proto.contractregistry.GetContractDeployedBytecodeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetMethodsBySelectorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.GetMethodsBySelectorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetMethodsBySelectorRequest.displayName = 'proto.contractregistry.GetMethodsBySelectorRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetMethodsBySelectorResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contractregistry.GetMethodsBySelectorResponse.repeatedFields_, null);
};
goog.inherits(proto.contractregistry.GetMethodsBySelectorResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetMethodsBySelectorResponse.displayName = 'proto.contractregistry.GetMethodsBySelectorResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetEventsBySigHashRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.GetEventsBySigHashRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetEventsBySigHashRequest.displayName = 'proto.contractregistry.GetEventsBySigHashRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.GetEventsBySigHashResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contractregistry.GetEventsBySigHashResponse.repeatedFields_, null);
};
goog.inherits(proto.contractregistry.GetEventsBySigHashResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.GetEventsBySigHashResponse.displayName = 'proto.contractregistry.GetEventsBySigHashResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.AddressUpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.AddressUpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.AddressUpdateRequest.displayName = 'proto.contractregistry.AddressUpdateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contractregistry.AddressUpdateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contractregistry.AddressUpdateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contractregistry.AddressUpdateResponse.displayName = 'proto.contractregistry.AddressUpdateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.RegisterContractRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.RegisterContractRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.RegisterContractRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.RegisterContractRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    contract: (f = msg.getContract()) && types_abi_abi_pb.Contract.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.RegisterContractRequest}
 */
proto.contractregistry.RegisterContractRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.RegisterContractRequest;
  return proto.contractregistry.RegisterContractRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.RegisterContractRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.RegisterContractRequest}
 */
proto.contractregistry.RegisterContractRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_abi_abi_pb.Contract;
      reader.readMessage(value,types_abi_abi_pb.Contract.deserializeBinaryFromReader);
      msg.setContract(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.RegisterContractRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.RegisterContractRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.RegisterContractRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.RegisterContractRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContract();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_abi_abi_pb.Contract.serializeBinaryToWriter
    );
  }
};


/**
 * optional abi.Contract contract = 1;
 * @return {?proto.abi.Contract}
 */
proto.contractregistry.RegisterContractRequest.prototype.getContract = function() {
  return /** @type{?proto.abi.Contract} */ (
    jspb.Message.getWrapperField(this, types_abi_abi_pb.Contract, 1));
};


/** @param {?proto.abi.Contract|undefined} value */
proto.contractregistry.RegisterContractRequest.prototype.setContract = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.contractregistry.RegisterContractRequest.prototype.clearContract = function() {
  this.setContract(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contractregistry.RegisterContractRequest.prototype.hasContract = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.RegisterContractResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.RegisterContractResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.RegisterContractResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.RegisterContractResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.RegisterContractResponse}
 */
proto.contractregistry.RegisterContractResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.RegisterContractResponse;
  return proto.contractregistry.RegisterContractResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.RegisterContractResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.RegisterContractResponse}
 */
proto.contractregistry.RegisterContractResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.RegisterContractResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.RegisterContractResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.RegisterContractResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.RegisterContractResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetContractRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetContractRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetContractRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    contract: (f = msg.getContract()) && types_abi_abi_pb.Contract.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetContractRequest}
 */
proto.contractregistry.GetContractRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetContractRequest;
  return proto.contractregistry.GetContractRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetContractRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetContractRequest}
 */
proto.contractregistry.GetContractRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_abi_abi_pb.Contract;
      reader.readMessage(value,types_abi_abi_pb.Contract.deserializeBinaryFromReader);
      msg.setContract(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetContractRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetContractRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContract();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_abi_abi_pb.Contract.serializeBinaryToWriter
    );
  }
};


/**
 * optional abi.Contract contract = 1;
 * @return {?proto.abi.Contract}
 */
proto.contractregistry.GetContractRequest.prototype.getContract = function() {
  return /** @type{?proto.abi.Contract} */ (
    jspb.Message.getWrapperField(this, types_abi_abi_pb.Contract, 1));
};


/** @param {?proto.abi.Contract|undefined} value */
proto.contractregistry.GetContractRequest.prototype.setContract = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.contractregistry.GetContractRequest.prototype.clearContract = function() {
  this.setContract(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contractregistry.GetContractRequest.prototype.hasContract = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetContractABIResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetContractABIResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetContractABIResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractABIResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    abi: msg.getAbi_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetContractABIResponse}
 */
proto.contractregistry.GetContractABIResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetContractABIResponse;
  return proto.contractregistry.GetContractABIResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetContractABIResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetContractABIResponse}
 */
proto.contractregistry.GetContractABIResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAbi(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractABIResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetContractABIResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetContractABIResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractABIResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAbi_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes abi = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetContractABIResponse.prototype.getAbi = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes abi = 1;
 * This is a type-conversion wrapper around `getAbi()`
 * @return {string}
 */
proto.contractregistry.GetContractABIResponse.prototype.getAbi_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAbi()));
};


/**
 * optional bytes abi = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAbi()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractABIResponse.prototype.getAbi_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAbi()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetContractABIResponse.prototype.setAbi = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetContractBytecodeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetContractBytecodeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetContractBytecodeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractBytecodeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    bytecode: msg.getBytecode_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetContractBytecodeResponse}
 */
proto.contractregistry.GetContractBytecodeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetContractBytecodeResponse;
  return proto.contractregistry.GetContractBytecodeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetContractBytecodeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetContractBytecodeResponse}
 */
proto.contractregistry.GetContractBytecodeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytecode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractBytecodeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetContractBytecodeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetContractBytecodeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractBytecodeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBytecode_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes bytecode = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetContractBytecodeResponse.prototype.getBytecode = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes bytecode = 1;
 * This is a type-conversion wrapper around `getBytecode()`
 * @return {string}
 */
proto.contractregistry.GetContractBytecodeResponse.prototype.getBytecode_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytecode()));
};


/**
 * optional bytes bytecode = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytecode()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractBytecodeResponse.prototype.getBytecode_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytecode()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetContractBytecodeResponse.prototype.setBytecode = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetContractDeployedBytecodeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetContractDeployedBytecodeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    deployedbytecode: msg.getDeployedbytecode_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetContractDeployedBytecodeResponse}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetContractDeployedBytecodeResponse;
  return proto.contractregistry.GetContractDeployedBytecodeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetContractDeployedBytecodeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetContractDeployedBytecodeResponse}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setDeployedbytecode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetContractDeployedBytecodeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetContractDeployedBytecodeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeployedbytecode_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes deployedBytecode = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.prototype.getDeployedbytecode = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes deployedBytecode = 1;
 * This is a type-conversion wrapper around `getDeployedbytecode()`
 * @return {string}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.prototype.getDeployedbytecode_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getDeployedbytecode()));
};


/**
 * optional bytes deployedBytecode = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getDeployedbytecode()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetContractDeployedBytecodeResponse.prototype.getDeployedbytecode_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getDeployedbytecode()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetContractDeployedBytecodeResponse.prototype.setDeployedbytecode = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetMethodsBySelectorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetMethodsBySelectorRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetMethodsBySelectorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    selector: msg.getSelector_asB64(),
    accountinstance: (f = msg.getAccountinstance()) && types_common_account_pb.AccountInstance.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetMethodsBySelectorRequest}
 */
proto.contractregistry.GetMethodsBySelectorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetMethodsBySelectorRequest;
  return proto.contractregistry.GetMethodsBySelectorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetMethodsBySelectorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetMethodsBySelectorRequest}
 */
proto.contractregistry.GetMethodsBySelectorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSelector(value);
      break;
    case 2:
      var value = new types_common_account_pb.AccountInstance;
      reader.readMessage(value,types_common_account_pb.AccountInstance.deserializeBinaryFromReader);
      msg.setAccountinstance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetMethodsBySelectorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetMethodsBySelectorRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetMethodsBySelectorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSelector_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getAccountinstance();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      types_common_account_pb.AccountInstance.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes selector = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.getSelector = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes selector = 1;
 * This is a type-conversion wrapper around `getSelector()`
 * @return {string}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.getSelector_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSelector()));
};


/**
 * optional bytes selector = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSelector()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.getSelector_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSelector()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.setSelector = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional common.AccountInstance accountInstance = 2;
 * @return {?proto.common.AccountInstance}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.getAccountinstance = function() {
  return /** @type{?proto.common.AccountInstance} */ (
    jspb.Message.getWrapperField(this, types_common_account_pb.AccountInstance, 2));
};


/** @param {?proto.common.AccountInstance|undefined} value */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.setAccountinstance = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.clearAccountinstance = function() {
  this.setAccountinstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contractregistry.GetMethodsBySelectorRequest.prototype.hasAccountinstance = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contractregistry.GetMethodsBySelectorResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetMethodsBySelectorResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetMethodsBySelectorResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetMethodsBySelectorResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    method: msg.getMethod_asB64(),
    defaultmethodsList: msg.getDefaultmethodsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetMethodsBySelectorResponse}
 */
proto.contractregistry.GetMethodsBySelectorResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetMethodsBySelectorResponse;
  return proto.contractregistry.GetMethodsBySelectorResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetMethodsBySelectorResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetMethodsBySelectorResponse}
 */
proto.contractregistry.GetMethodsBySelectorResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMethod(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addDefaultmethods(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetMethodsBySelectorResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetMethodsBySelectorResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetMethodsBySelectorResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMethod_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getDefaultmethodsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
};


/**
 * optional bytes method = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.getMethod = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes method = 1;
 * This is a type-conversion wrapper around `getMethod()`
 * @return {string}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.getMethod_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMethod()));
};


/**
 * optional bytes method = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMethod()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.getMethod_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMethod()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.setMethod = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * repeated bytes defaultMethods = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.getDefaultmethodsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes defaultMethods = 2;
 * This is a type-conversion wrapper around `getDefaultmethodsList()`
 * @return {!Array<string>}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.getDefaultmethodsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getDefaultmethodsList()));
};


/**
 * repeated bytes defaultMethods = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getDefaultmethodsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.getDefaultmethodsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getDefaultmethodsList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.setDefaultmethodsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.addDefaultmethods = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.contractregistry.GetMethodsBySelectorResponse.prototype.clearDefaultmethodsList = function() {
  this.setDefaultmethodsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetEventsBySigHashRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetEventsBySigHashRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetEventsBySigHashRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sighash: msg.getSighash_asB64(),
    accountinstance: (f = msg.getAccountinstance()) && types_common_account_pb.AccountInstance.toObject(includeInstance, f),
    indexedinputcount: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetEventsBySigHashRequest}
 */
proto.contractregistry.GetEventsBySigHashRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetEventsBySigHashRequest;
  return proto.contractregistry.GetEventsBySigHashRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetEventsBySigHashRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetEventsBySigHashRequest}
 */
proto.contractregistry.GetEventsBySigHashRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSighash(value);
      break;
    case 2:
      var value = new types_common_account_pb.AccountInstance;
      reader.readMessage(value,types_common_account_pb.AccountInstance.deserializeBinaryFromReader);
      msg.setAccountinstance(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIndexedinputcount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetEventsBySigHashRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetEventsBySigHashRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetEventsBySigHashRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSighash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getAccountinstance();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      types_common_account_pb.AccountInstance.serializeBinaryToWriter
    );
  }
  f = message.getIndexedinputcount();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional bytes sigHash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.getSighash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes sigHash = 1;
 * This is a type-conversion wrapper around `getSighash()`
 * @return {string}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.getSighash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSighash()));
};


/**
 * optional bytes sigHash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSighash()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.getSighash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSighash()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetEventsBySigHashRequest.prototype.setSighash = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional common.AccountInstance accountInstance = 2;
 * @return {?proto.common.AccountInstance}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.getAccountinstance = function() {
  return /** @type{?proto.common.AccountInstance} */ (
    jspb.Message.getWrapperField(this, types_common_account_pb.AccountInstance, 2));
};


/** @param {?proto.common.AccountInstance|undefined} value */
proto.contractregistry.GetEventsBySigHashRequest.prototype.setAccountinstance = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.clearAccountinstance = function() {
  this.setAccountinstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.hasAccountinstance = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint32 indexedInputCount = 3;
 * @return {number}
 */
proto.contractregistry.GetEventsBySigHashRequest.prototype.getIndexedinputcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.contractregistry.GetEventsBySigHashRequest.prototype.setIndexedinputcount = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contractregistry.GetEventsBySigHashResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.GetEventsBySigHashResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.GetEventsBySigHashResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetEventsBySigHashResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    event: msg.getEvent_asB64(),
    defaulteventsList: msg.getDefaulteventsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.GetEventsBySigHashResponse}
 */
proto.contractregistry.GetEventsBySigHashResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.GetEventsBySigHashResponse;
  return proto.contractregistry.GetEventsBySigHashResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.GetEventsBySigHashResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.GetEventsBySigHashResponse}
 */
proto.contractregistry.GetEventsBySigHashResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEvent(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addDefaultevents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.GetEventsBySigHashResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.GetEventsBySigHashResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.GetEventsBySigHashResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getDefaulteventsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
};


/**
 * optional bytes event = 1;
 * @return {!(string|Uint8Array)}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.getEvent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes event = 1;
 * This is a type-conversion wrapper around `getEvent()`
 * @return {string}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.getEvent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEvent()));
};


/**
 * optional bytes event = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEvent()`
 * @return {!Uint8Array}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.getEvent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEvent()));
};


/** @param {!(string|Uint8Array)} value */
proto.contractregistry.GetEventsBySigHashResponse.prototype.setEvent = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * repeated bytes defaultEvents = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.getDefaulteventsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes defaultEvents = 2;
 * This is a type-conversion wrapper around `getDefaulteventsList()`
 * @return {!Array<string>}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.getDefaulteventsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getDefaulteventsList()));
};


/**
 * repeated bytes defaultEvents = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getDefaulteventsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.getDefaulteventsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getDefaulteventsList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.contractregistry.GetEventsBySigHashResponse.prototype.setDefaulteventsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.addDefaultevents = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.contractregistry.GetEventsBySigHashResponse.prototype.clearDefaulteventsList = function() {
  this.setDefaulteventsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.AddressUpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.AddressUpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.AddressUpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.AddressUpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountinstance: (f = msg.getAccountinstance()) && types_common_account_pb.AccountInstance.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.AddressUpdateRequest}
 */
proto.contractregistry.AddressUpdateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.AddressUpdateRequest;
  return proto.contractregistry.AddressUpdateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.AddressUpdateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.AddressUpdateRequest}
 */
proto.contractregistry.AddressUpdateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_common_account_pb.AccountInstance;
      reader.readMessage(value,types_common_account_pb.AccountInstance.deserializeBinaryFromReader);
      msg.setAccountinstance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.AddressUpdateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.AddressUpdateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.AddressUpdateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.AddressUpdateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountinstance();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_common_account_pb.AccountInstance.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.AccountInstance accountInstance = 1;
 * @return {?proto.common.AccountInstance}
 */
proto.contractregistry.AddressUpdateRequest.prototype.getAccountinstance = function() {
  return /** @type{?proto.common.AccountInstance} */ (
    jspb.Message.getWrapperField(this, types_common_account_pb.AccountInstance, 1));
};


/** @param {?proto.common.AccountInstance|undefined} value */
proto.contractregistry.AddressUpdateRequest.prototype.setAccountinstance = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.contractregistry.AddressUpdateRequest.prototype.clearAccountinstance = function() {
  this.setAccountinstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contractregistry.AddressUpdateRequest.prototype.hasAccountinstance = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contractregistry.AddressUpdateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contractregistry.AddressUpdateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contractregistry.AddressUpdateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.AddressUpdateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contractregistry.AddressUpdateResponse}
 */
proto.contractregistry.AddressUpdateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contractregistry.AddressUpdateResponse;
  return proto.contractregistry.AddressUpdateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contractregistry.AddressUpdateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contractregistry.AddressUpdateResponse}
 */
proto.contractregistry.AddressUpdateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contractregistry.AddressUpdateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contractregistry.AddressUpdateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contractregistry.AddressUpdateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contractregistry.AddressUpdateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.contractregistry);
