// source: types/ethereum/receipt.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var types_ethereum_base_pb = require('../../types/ethereum/base_pb.js');
goog.object.extend(proto, types_ethereum_base_pb);
goog.exportSymbol('proto.ethereum.Log', null, global);
goog.exportSymbol('proto.ethereum.Receipt', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ethereum.Log = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ethereum.Log.repeatedFields_, null);
};
goog.inherits(proto.ethereum.Log, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ethereum.Log.displayName = 'proto.ethereum.Log';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ethereum.Receipt = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ethereum.Receipt.repeatedFields_, null);
};
goog.inherits(proto.ethereum.Receipt, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ethereum.Receipt.displayName = 'proto.ethereum.Receipt';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ethereum.Log.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ethereum.Log.prototype.toObject = function(opt_includeInstance) {
  return proto.ethereum.Log.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ethereum.Log} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ethereum.Log.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: (f = msg.getAddress()) && types_ethereum_base_pb.Account.toObject(includeInstance, f),
    topicsList: jspb.Message.toObjectList(msg.getTopicsList(),
    types_ethereum_base_pb.Hash.toObject, includeInstance),
    data: msg.getData_asB64(),
    event: jspb.Message.getFieldWithDefault(msg, 4, ""),
    decodedDataMap: (f = msg.getDecodedDataMap()) ? f.toObject(includeInstance, undefined) : [],
    blockNumber: jspb.Message.getFieldWithDefault(msg, 6, 0),
    txHash: (f = msg.getTxHash()) && types_ethereum_base_pb.Hash.toObject(includeInstance, f),
    txIndex: jspb.Message.getFieldWithDefault(msg, 8, 0),
    blockHash: (f = msg.getBlockHash()) && types_ethereum_base_pb.Hash.toObject(includeInstance, f),
    index: jspb.Message.getFieldWithDefault(msg, 10, 0),
    removed: jspb.Message.getBooleanFieldWithDefault(msg, 11, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ethereum.Log}
 */
proto.ethereum.Log.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ethereum.Log;
  return proto.ethereum.Log.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ethereum.Log} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ethereum.Log}
 */
proto.ethereum.Log.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_ethereum_base_pb.Account;
      reader.readMessage(value,types_ethereum_base_pb.Account.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 2:
      var value = new types_ethereum_base_pb.Hash;
      reader.readMessage(value,types_ethereum_base_pb.Hash.deserializeBinaryFromReader);
      msg.addTopics(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvent(value);
      break;
    case 5:
      var value = msg.getDecodedDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockNumber(value);
      break;
    case 7:
      var value = new types_ethereum_base_pb.Hash;
      reader.readMessage(value,types_ethereum_base_pb.Hash.deserializeBinaryFromReader);
      msg.setTxHash(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTxIndex(value);
      break;
    case 9:
      var value = new types_ethereum_base_pb.Hash;
      reader.readMessage(value,types_ethereum_base_pb.Hash.deserializeBinaryFromReader);
      msg.setBlockHash(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIndex(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoved(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ethereum.Log.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ethereum.Log.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ethereum.Log} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ethereum.Log.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_ethereum_base_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getTopicsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      types_ethereum_base_pb.Hash.serializeBinaryToWriter
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getEvent();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDecodedDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getBlockNumber();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getTxHash();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      types_ethereum_base_pb.Hash.serializeBinaryToWriter
    );
  }
  f = message.getTxIndex();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getBlockHash();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      types_ethereum_base_pb.Hash.serializeBinaryToWriter
    );
  }
  f = message.getIndex();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getRemoved();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
};


/**
 * optional Account address = 1;
 * @return {?proto.ethereum.Account}
 */
proto.ethereum.Log.prototype.getAddress = function() {
  return /** @type{?proto.ethereum.Account} */ (
    jspb.Message.getWrapperField(this, types_ethereum_base_pb.Account, 1));
};


/**
 * @param {?proto.ethereum.Account|undefined} value
 * @return {!proto.ethereum.Log} returns this
*/
proto.ethereum.Log.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ethereum.Log.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Hash topics = 2;
 * @return {!Array<!proto.ethereum.Hash>}
 */
proto.ethereum.Log.prototype.getTopicsList = function() {
  return /** @type{!Array<!proto.ethereum.Hash>} */ (
    jspb.Message.getRepeatedWrapperField(this, types_ethereum_base_pb.Hash, 2));
};


/**
 * @param {!Array<!proto.ethereum.Hash>} value
 * @return {!proto.ethereum.Log} returns this
*/
proto.ethereum.Log.prototype.setTopicsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ethereum.Hash=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ethereum.Hash}
 */
proto.ethereum.Log.prototype.addTopics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ethereum.Hash, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.clearTopicsList = function() {
  return this.setTopicsList([]);
};


/**
 * optional bytes data = 3;
 * @return {!(string|Uint8Array)}
 */
proto.ethereum.Log.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes data = 3;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.ethereum.Log.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.ethereum.Log.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string event = 4;
 * @return {string}
 */
proto.ethereum.Log.prototype.getEvent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.setEvent = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * map<string, string> decoded_data = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ethereum.Log.prototype.getDecodedDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.clearDecodedDataMap = function() {
  this.getDecodedDataMap().clear();
  return this;};


/**
 * optional uint64 block_number = 6;
 * @return {number}
 */
proto.ethereum.Log.prototype.getBlockNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.setBlockNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional Hash tx_hash = 7;
 * @return {?proto.ethereum.Hash}
 */
proto.ethereum.Log.prototype.getTxHash = function() {
  return /** @type{?proto.ethereum.Hash} */ (
    jspb.Message.getWrapperField(this, types_ethereum_base_pb.Hash, 7));
};


/**
 * @param {?proto.ethereum.Hash|undefined} value
 * @return {!proto.ethereum.Log} returns this
*/
proto.ethereum.Log.prototype.setTxHash = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.clearTxHash = function() {
  return this.setTxHash(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ethereum.Log.prototype.hasTxHash = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint64 tx_index = 8;
 * @return {number}
 */
proto.ethereum.Log.prototype.getTxIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.setTxIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional Hash block_hash = 9;
 * @return {?proto.ethereum.Hash}
 */
proto.ethereum.Log.prototype.getBlockHash = function() {
  return /** @type{?proto.ethereum.Hash} */ (
    jspb.Message.getWrapperField(this, types_ethereum_base_pb.Hash, 9));
};


/**
 * @param {?proto.ethereum.Hash|undefined} value
 * @return {!proto.ethereum.Log} returns this
*/
proto.ethereum.Log.prototype.setBlockHash = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.clearBlockHash = function() {
  return this.setBlockHash(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ethereum.Log.prototype.hasBlockHash = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional uint64 index = 10;
 * @return {number}
 */
proto.ethereum.Log.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.setIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional bool removed = 11;
 * @return {boolean}
 */
proto.ethereum.Log.prototype.getRemoved = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ethereum.Log} returns this
 */
proto.ethereum.Log.prototype.setRemoved = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ethereum.Receipt.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ethereum.Receipt.prototype.toObject = function(opt_includeInstance) {
  return proto.ethereum.Receipt.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ethereum.Receipt} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ethereum.Receipt.toObject = function(includeInstance, msg) {
  var f, obj = {
    txHash: (f = msg.getTxHash()) && types_ethereum_base_pb.Hash.toObject(includeInstance, f),
    blockHash: (f = msg.getBlockHash()) && types_ethereum_base_pb.Hash.toObject(includeInstance, f),
    blockNumber: jspb.Message.getFieldWithDefault(msg, 3, 0),
    txIndex: jspb.Message.getFieldWithDefault(msg, 4, 0),
    contractAddress: (f = msg.getContractAddress()) && types_ethereum_base_pb.Account.toObject(includeInstance, f),
    postState: msg.getPostState_asB64(),
    status: jspb.Message.getFieldWithDefault(msg, 8, 0),
    bloom: msg.getBloom_asB64(),
    logsList: jspb.Message.toObjectList(msg.getLogsList(),
    proto.ethereum.Log.toObject, includeInstance),
    gasUsed: jspb.Message.getFieldWithDefault(msg, 12, 0),
    cumulativeGasUsed: jspb.Message.getFieldWithDefault(msg, 13, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ethereum.Receipt}
 */
proto.ethereum.Receipt.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ethereum.Receipt;
  return proto.ethereum.Receipt.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ethereum.Receipt} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ethereum.Receipt}
 */
proto.ethereum.Receipt.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_ethereum_base_pb.Hash;
      reader.readMessage(value,types_ethereum_base_pb.Hash.deserializeBinaryFromReader);
      msg.setTxHash(value);
      break;
    case 2:
      var value = new types_ethereum_base_pb.Hash;
      reader.readMessage(value,types_ethereum_base_pb.Hash.deserializeBinaryFromReader);
      msg.setBlockHash(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockNumber(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTxIndex(value);
      break;
    case 6:
      var value = new types_ethereum_base_pb.Account;
      reader.readMessage(value,types_ethereum_base_pb.Account.deserializeBinaryFromReader);
      msg.setContractAddress(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPostState(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStatus(value);
      break;
    case 10:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBloom(value);
      break;
    case 11:
      var value = new proto.ethereum.Log;
      reader.readMessage(value,proto.ethereum.Log.deserializeBinaryFromReader);
      msg.addLogs(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGasUsed(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCumulativeGasUsed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ethereum.Receipt.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ethereum.Receipt.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ethereum.Receipt} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ethereum.Receipt.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxHash();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_ethereum_base_pb.Hash.serializeBinaryToWriter
    );
  }
  f = message.getBlockHash();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      types_ethereum_base_pb.Hash.serializeBinaryToWriter
    );
  }
  f = message.getBlockNumber();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getTxIndex();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getContractAddress();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      types_ethereum_base_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getPostState_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getBloom_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      10,
      f
    );
  }
  f = message.getLogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.ethereum.Log.serializeBinaryToWriter
    );
  }
  f = message.getGasUsed();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getCumulativeGasUsed();
  if (f !== 0) {
    writer.writeUint64(
      13,
      f
    );
  }
};


/**
 * optional Hash tx_hash = 1;
 * @return {?proto.ethereum.Hash}
 */
proto.ethereum.Receipt.prototype.getTxHash = function() {
  return /** @type{?proto.ethereum.Hash} */ (
    jspb.Message.getWrapperField(this, types_ethereum_base_pb.Hash, 1));
};


/**
 * @param {?proto.ethereum.Hash|undefined} value
 * @return {!proto.ethereum.Receipt} returns this
*/
proto.ethereum.Receipt.prototype.setTxHash = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.clearTxHash = function() {
  return this.setTxHash(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ethereum.Receipt.prototype.hasTxHash = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Hash block_hash = 2;
 * @return {?proto.ethereum.Hash}
 */
proto.ethereum.Receipt.prototype.getBlockHash = function() {
  return /** @type{?proto.ethereum.Hash} */ (
    jspb.Message.getWrapperField(this, types_ethereum_base_pb.Hash, 2));
};


/**
 * @param {?proto.ethereum.Hash|undefined} value
 * @return {!proto.ethereum.Receipt} returns this
*/
proto.ethereum.Receipt.prototype.setBlockHash = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.clearBlockHash = function() {
  return this.setBlockHash(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ethereum.Receipt.prototype.hasBlockHash = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint64 block_number = 3;
 * @return {number}
 */
proto.ethereum.Receipt.prototype.getBlockNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setBlockNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 tx_index = 4;
 * @return {number}
 */
proto.ethereum.Receipt.prototype.getTxIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setTxIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional Account contract_address = 6;
 * @return {?proto.ethereum.Account}
 */
proto.ethereum.Receipt.prototype.getContractAddress = function() {
  return /** @type{?proto.ethereum.Account} */ (
    jspb.Message.getWrapperField(this, types_ethereum_base_pb.Account, 6));
};


/**
 * @param {?proto.ethereum.Account|undefined} value
 * @return {!proto.ethereum.Receipt} returns this
*/
proto.ethereum.Receipt.prototype.setContractAddress = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.clearContractAddress = function() {
  return this.setContractAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ethereum.Receipt.prototype.hasContractAddress = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bytes post_state = 7;
 * @return {!(string|Uint8Array)}
 */
proto.ethereum.Receipt.prototype.getPostState = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes post_state = 7;
 * This is a type-conversion wrapper around `getPostState()`
 * @return {string}
 */
proto.ethereum.Receipt.prototype.getPostState_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPostState()));
};


/**
 * optional bytes post_state = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPostState()`
 * @return {!Uint8Array}
 */
proto.ethereum.Receipt.prototype.getPostState_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPostState()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setPostState = function(value) {
  return jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional uint64 status = 8;
 * @return {number}
 */
proto.ethereum.Receipt.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bytes bloom = 10;
 * @return {!(string|Uint8Array)}
 */
proto.ethereum.Receipt.prototype.getBloom = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * optional bytes bloom = 10;
 * This is a type-conversion wrapper around `getBloom()`
 * @return {string}
 */
proto.ethereum.Receipt.prototype.getBloom_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBloom()));
};


/**
 * optional bytes bloom = 10;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBloom()`
 * @return {!Uint8Array}
 */
proto.ethereum.Receipt.prototype.getBloom_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBloom()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setBloom = function(value) {
  return jspb.Message.setProto3BytesField(this, 10, value);
};


/**
 * repeated Log logs = 11;
 * @return {!Array<!proto.ethereum.Log>}
 */
proto.ethereum.Receipt.prototype.getLogsList = function() {
  return /** @type{!Array<!proto.ethereum.Log>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ethereum.Log, 11));
};


/**
 * @param {!Array<!proto.ethereum.Log>} value
 * @return {!proto.ethereum.Receipt} returns this
*/
proto.ethereum.Receipt.prototype.setLogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.ethereum.Log=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ethereum.Log}
 */
proto.ethereum.Receipt.prototype.addLogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.ethereum.Log, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.clearLogsList = function() {
  return this.setLogsList([]);
};


/**
 * optional uint64 gas_used = 12;
 * @return {number}
 */
proto.ethereum.Receipt.prototype.getGasUsed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setGasUsed = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional uint64 cumulative_gas_used = 13;
 * @return {number}
 */
proto.ethereum.Receipt.prototype.getCumulativeGasUsed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.ethereum.Receipt} returns this
 */
proto.ethereum.Receipt.prototype.setCumulativeGasUsed = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


goog.object.extend(exports, proto.ethereum);
